"""Generate the Network Engineer Agent setup & usage guide as a PDF."""

from fpdf import FPDF


class GuidePDF(FPDF):
    DARK_BG = (30, 30, 30)
    CARD_BG = (45, 45, 45)
    ACCENT = (0, 150, 255)
    TEXT = (230, 230, 230)
    MUTED = (160, 160, 160)
    GREEN = (0, 200, 100)
    YELLOW = (255, 200, 0)
    WHITE = (255, 255, 255)

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        if self.page_no() == 1:
            return
        self.set_fill_color(*self.DARK_BG)
        self.rect(0, 0, 210, 297, "F")
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*self.MUTED)
        self.set_y(5)
        self.cell(0, 5, "NetworkAgent  |  Setup & Operations Guide", align="L")
        self.cell(0, 5, f"Page {self.page_no()}", align="R")
        self.ln(10)

    def footer(self):
        if self.page_no() == 1:
            return
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*self.MUTED)
        self.cell(0, 10, "Confidential  -  Generated by NetworkAgent", align="C")

    def cover_page(self):
        self.add_page()
        self.set_fill_color(20, 20, 35)
        self.rect(0, 0, 210, 297, "F")

        # Accent bar
        self.set_fill_color(*self.ACCENT)
        self.rect(0, 80, 210, 4, "F")

        # Title
        self.set_y(95)
        self.set_font("Helvetica", "B", 36)
        self.set_text_color(*self.WHITE)
        self.cell(0, 18, "NetworkAgent", align="C", new_x="LMARGIN", new_y="NEXT")

        self.set_font("Helvetica", "", 16)
        self.set_text_color(*self.ACCENT)
        self.cell(0, 10, "AI-Powered Network Operations Agent", align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(8)
        self.set_font("Helvetica", "", 12)
        self.set_text_color(*self.MUTED)
        self.cell(0, 8, "Setup, Launch & Connection Guide", align="C", new_x="LMARGIN", new_y="NEXT")

        # Feature pills
        self.ln(20)
        pills = ["CLI", "Web Dashboard", "AI Chat", "Automation", "SNMP", "SSH", "NETCONF", "RESTCONF"]
        self.set_font("Helvetica", "B", 9)
        total_w = len(pills) * 22
        x_start = (210 - total_w) / 2
        self.set_x(x_start)
        for pill in pills:
            self.set_fill_color(*self.ACCENT)
            self.set_text_color(*self.WHITE)
            w = self.get_string_width(pill) + 8
            self.cell(w, 8, pill, fill=True, align="C")
            self.set_x(self.get_x() + 3)

        # Bottom info
        self.set_y(240)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.MUTED)
        self.cell(0, 7, "92 Files  |  24,000+ Lines  |  8 Vendor Platforms  |  17 Automation Actions", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 7, "Version 1.0", align="C")

    def section_title(self, number, title):
        self.ln(6)
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(*self.ACCENT)
        self.cell(0, 12, f"{number}. {title}", new_x="LMARGIN", new_y="NEXT")
        # Underline
        self.set_fill_color(*self.ACCENT)
        self.rect(10, self.get_y(), 60, 1, "F")
        self.ln(6)

    def sub_title(self, title):
        self.ln(3)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*self.GREEN)
        self.cell(0, 9, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def body_text(self, text):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.TEXT)
        self.multi_cell(0, 6, text)
        self.ln(2)

    def code_block(self, code):
        self.set_fill_color(20, 20, 20)
        self.set_font("Courier", "", 9)
        self.set_text_color(*self.GREEN)
        lines = code.strip().split("\n")
        block_h = len(lines) * 6 + 8
        y_start = self.get_y()
        self.rect(15, y_start, 180, block_h, "F")
        self.set_xy(19, y_start + 4)
        for line in lines:
            self.cell(0, 6, line, new_x="LMARGIN", new_y="NEXT")
            self.set_x(19)
        self.set_y(y_start + block_h + 3)

    def bullet(self, text, indent=0):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.TEXT)
        x = 15 + indent
        self.set_x(x)
        self.set_text_color(*self.ACCENT)
        self.cell(5, 6, ">")
        self.set_text_color(*self.TEXT)
        self.multi_cell(175 - indent, 6, text)
        self.ln(1)

    def numbered_step(self, num, title, description):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*self.ACCENT)
        self.set_fill_color(*self.CARD_BG)

        y = self.get_y()
        # Step number circle
        self.set_fill_color(*self.ACCENT)
        self.set_text_color(*self.WHITE)
        self.set_font("Helvetica", "B", 10)
        self.cell(8, 8, str(num), fill=True, align="C")
        self.set_x(28)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*self.WHITE)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")

        self.set_x(28)
        self.set_font("Helvetica", "", 9.5)
        self.set_text_color(*self.MUTED)
        self.multi_cell(165, 5.5, description)
        self.ln(3)

    def info_box(self, title, text):
        self.set_fill_color(25, 50, 80)
        y = self.get_y()
        self.rect(15, y, 180, 6 + 6 * (len(text) // 80 + 1) + 6, "F")
        self.set_xy(19, y + 3)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*self.YELLOW)
        self.cell(0, 6, title, new_x="LMARGIN", new_y="NEXT")
        self.set_x(19)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*self.TEXT)
        self.multi_cell(172, 6, text)
        self.ln(4)

    def table_row(self, cols, widths, bold=False, header=False):
        if header:
            self.set_fill_color(*self.ACCENT)
            self.set_text_color(*self.WHITE)
            self.set_font("Helvetica", "B", 9)
        elif bold:
            self.set_fill_color(*self.CARD_BG)
            self.set_text_color(*self.WHITE)
            self.set_font("Helvetica", "B", 9)
        else:
            self.set_fill_color(38, 38, 38)
            self.set_text_color(*self.TEXT)
            self.set_font("Helvetica", "", 9)

        for i, (col, w) in enumerate(zip(cols, widths)):
            self.cell(w, 7, col, border=0, fill=True, align="L" if i == 0 else "L")
        self.ln()


def build_guide():
    pdf = GuidePDF()

    # ===== COVER =====
    pdf.cover_page()

    # ===== TABLE OF CONTENTS =====
    pdf.add_page()
    pdf.section_title("", "Table of Contents")
    toc = [
        ("1", "Prerequisites & Requirements"),
        ("2", "Installation"),
        ("3", "Initialize the Project"),
        ("4", "Launch Interfaces"),
        ("5", "Adding Your First Device"),
        ("6", "Storing Credentials"),
        ("7", "Connecting to Devices"),
        ("8", "Configuration Management"),
        ("9", "Monitoring & Alerts"),
        ("10", "Automation & Runbooks"),
        ("11", "AI Chat Agent"),
        ("12", "Supported Vendors & Platforms"),
        ("13", "Project Structure"),
        ("14", "Troubleshooting"),
    ]
    for num, title in toc:
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(*pdf.TEXT)
        pdf.set_x(20)
        pdf.set_text_color(*pdf.ACCENT)
        pdf.cell(12, 8, num + ".")
        pdf.set_text_color(*pdf.TEXT)
        dots = "." * (60 - len(title))
        pdf.cell(0, 8, f"{title}  {dots}", new_x="LMARGIN", new_y="NEXT")

    # ===== SECTION 1: PREREQUISITES =====
    pdf.add_page()
    pdf.section_title("1", "Prerequisites & Requirements")

    pdf.sub_title("System Requirements")
    pdf.bullet("Python 3.10 or higher")
    pdf.bullet("pip package manager")
    pdf.bullet("Network access to target devices (SSH/SNMP/HTTPS)")
    pdf.bullet("Windows, Linux, or macOS")

    pdf.sub_title("Required Python Packages")
    pdf.body_text("All dependencies are listed in requirements.txt and will be installed automatically:")
    pkgs = [
        ("fastapi + uvicorn", "Web dashboard & REST API"),
        ("typer + rich", "CLI interface"),
        ("netmiko", "SSH device connections"),
        ("pysnmp", "SNMP polling & discovery"),
        ("ncclient", "NETCONF device management"),
        ("httpx", "RESTCONF & HTTP requests"),
        ("aiosqlite", "Async SQLite database"),
        ("cryptography (Fernet)", "Credential encryption"),
        ("pyyaml", "Runbook YAML parsing"),
        ("apscheduler", "Scheduled job execution"),
        ("anthropic", "Claude AI agent (optional)"),
    ]
    w = [60, 120]
    pdf.table_row(["Package", "Purpose"], w, header=True)
    for pkg, purpose in pkgs:
        pdf.table_row([pkg, purpose], w)

    pdf.ln(5)
    pdf.info_box("NOTE", "The AI Chat interface requires an Anthropic API key. Set it in your .env file as ANTHROPIC_API_KEY=sk-ant-...")

    # ===== SECTION 2: INSTALLATION =====
    pdf.add_page()
    pdf.section_title("2", "Installation")

    pdf.numbered_step(1, "Clone or copy the project", "Place the network_agent folder on your machine. The default location used in this guide is your Desktop.")

    pdf.numbered_step(2, "Open a terminal", "Navigate to the project directory:")
    pdf.code_block("cd network_agent")

    pdf.numbered_step(3, "Create a virtual environment (recommended)", "Isolate project dependencies from your system Python:")
    pdf.code_block("python -m venv venv\n\n# Windows:\nvenv\\Scripts\\activate\n\n# Linux/Mac:\nsource venv/bin/activate")

    pdf.numbered_step(4, "Install dependencies", "Install all required packages:")
    pdf.code_block("pip install -r requirements.txt")

    pdf.numbered_step(5, "Create your .env file", "Copy the example and fill in your settings:")
    pdf.code_block("copy .env.example .env\n\n# Edit .env with your settings:\n# ANTHROPIC_API_KEY=sk-ant-...  (for AI Chat)\n# SECRET_KEY=your-random-secret  (for JWT auth)\n# ENCRYPTION_KEY=               (auto-generated on init)")

    # ===== SECTION 3: INITIALIZE =====
    pdf.add_page()
    pdf.section_title("3", "Initialize the Project")

    pdf.body_text("The init command sets up the database, creates necessary directories, and generates your encryption key for credential storage.")

    pdf.code_block("python run.py init")

    pdf.sub_title("What init does:")
    pdf.bullet("Creates the SQLite database with 11 tables (devices, credentials, configs, metrics, alerts, audit_log, runbook_executions, scheduled_jobs, etc.)")
    pdf.bullet("Creates the data/runbooks/ directory and loads 5 sample runbooks")
    pdf.bullet("Generates a Fernet encryption key for secure credential storage")
    pdf.bullet("Sets up default alert rules (CPU > 90%, Memory > 85%, etc.)")

    pdf.ln(3)
    pdf.body_text("Expected output:")
    pdf.code_block("NetworkAgent initialized successfully.\n  Database: data/network_agent.db (11 tables)\n  Runbooks: data/runbooks/ (5 loaded)\n  Encryption key: generated\n  Ready to launch.")

    pdf.info_box("IMPORTANT", "Run init only once. Running it again is safe (it won't overwrite existing data), but it's not necessary after the first time.")

    # ===== SECTION 4: LAUNCH =====
    pdf.add_page()
    pdf.section_title("4", "Launch Interfaces")

    pdf.body_text("NetworkAgent provides three interfaces. You can run any of them independently.")

    pdf.sub_title("Option A: Web Dashboard")
    pdf.code_block("python run.py web")
    pdf.bullet("Opens a dark-themed single-page dashboard at http://localhost:8080")
    pdf.bullet("Real-time WebSocket updates for metrics, alerts, and automation events")
    pdf.bullet("Views: Dashboard, Devices, Config, Monitoring, Alerts, Discovery, Diagnostics, Automation, AI Chat")
    pdf.bullet("JWT authentication (default credentials in .env)")

    pdf.sub_title("Option B: CLI (Terminal)")
    pdf.code_block("python run.py cli")
    pdf.body_text("Full-featured terminal interface with Rich formatting. Use --help on any command:")
    pdf.code_block("python run.py cli --help\npython run.py cli device --help\npython run.py cli config --help\npython run.py cli monitor --help\npython run.py cli automation --help")

    pdf.sub_title("Option C: AI Chat")
    pdf.code_block("python run.py chat")
    pdf.bullet("Interactive Claude-powered agent with 17 network operation tools")
    pdf.bullet("Natural language: \"Show me all offline devices\" or \"Backup the config on switch-01\"")
    pdf.bullet("Safety classification: safe/write/destructive actions with confirmation gates")
    pdf.bullet("Requires ANTHROPIC_API_KEY in .env")

    # ===== SECTION 5: ADD DEVICE =====
    pdf.add_page()
    pdf.section_title("5", "Adding Your First Device")

    pdf.sub_title("Via CLI")
    pdf.code_block('python run.py cli device add \\\n  --hostname "core-switch-01" \\\n  --ip "192.168.1.1" \\\n  --type switch \\\n  --vendor cisco_ios \\\n  --model "Catalyst 9300" \\\n  --location "Server Room A"')

    pdf.sub_title("Via Web Dashboard")
    pdf.numbered_step(1, "Navigate to Devices tab", "Click 'Devices' in the sidebar")
    pdf.numbered_step(2, "Click '+ Add Device'", "Fill in the form with device details")
    pdf.numbered_step(3, "Save", "The device appears in the device table")

    pdf.sub_title("Via AI Chat")
    pdf.code_block('You: "Add a Cisco switch at 192.168.1.1 called core-switch-01"')

    pdf.sub_title("Supported Vendor Types")
    vendors = [
        ("cisco_ios", "Cisco IOS / IOS-XE switches & routers"),
        ("juniper_junos", "Juniper JunOS devices"),
        ("fortinet", "FortiGate firewalls"),
        ("paloalto", "Palo Alto Networks firewalls"),
        ("mikrotik", "MikroTik RouterOS"),
        ("aruba", "Aruba / HPE switches & APs"),
        ("pfsense", "pfSense firewalls"),
    ]
    w = [40, 140]
    pdf.table_row(["Vendor Key", "Platform"], w, header=True)
    for key, desc in vendors:
        pdf.table_row([key, desc], w)

    # ===== SECTION 6: CREDENTIALS =====
    pdf.add_page()
    pdf.section_title("6", "Storing Credentials")

    pdf.body_text("Credentials are encrypted with Fernet (AES-128-CBC) and stored in the database. Each credential set gets a unique ID that you assign to devices.")

    pdf.sub_title("Add SSH Credentials")
    pdf.code_block('python run.py cli credential add \\\n  --name "cisco-admin" \\\n  --username "admin" \\\n  --password "YourSecurePassword" \\\n  --enable-secret "EnablePassword"')

    pdf.sub_title("Add SNMP Community")
    pdf.code_block('python run.py cli credential add \\\n  --name "snmp-readonly" \\\n  --community "public" \\\n  --snmp-version "2c"')

    pdf.sub_title("Assign Credential to Device")
    pdf.code_block('python run.py cli device update core-switch-01 \\\n  --credential-id "cisco-admin"')

    pdf.info_box("SECURITY", "Credentials are encrypted at rest using Fernet symmetric encryption. The encryption key is stored in your .env file. Keep .env secure and never commit it to version control.")

    # ===== SECTION 7: CONNECTING =====
    pdf.add_page()
    pdf.section_title("7", "Connecting to Devices")

    pdf.body_text("Once a device has credentials assigned, NetworkAgent can connect via SSH, SNMP, NETCONF, or RESTCONF depending on the vendor driver.")

    pdf.sub_title("Test Connectivity")
    pdf.code_block("# Ping test\npython run.py cli diag ping 192.168.1.1\n\n# Port check (SSH)\npython run.py cli diag port-check 192.168.1.1 22\n\n# Port check (HTTPS/RESTCONF)\npython run.py cli diag port-check 192.168.1.1 443\n\n# Full health check\npython run.py cli diag health core-switch-01")

    pdf.sub_title("Run a Command on a Device")
    pdf.code_block('# Show running config\npython run.py cli troubleshoot run-command \\\n  --device core-switch-01 \\\n  --command "show running-config"\n\n# Show interfaces\npython run.py cli troubleshoot run-command \\\n  --device core-switch-01 \\\n  --command "show ip interface brief"')

    pdf.sub_title("Connection Protocols by Vendor")
    protos = [
        ("cisco_ios", "SSH (Netmiko)", "SNMP v2c/v3", "Yes", "Yes"),
        ("juniper_junos", "SSH (Netmiko)", "SNMP v2c/v3", "Yes", "Yes"),
        ("fortinet", "SSH (Netmiko)", "SNMP v2c", "No", "Yes"),
        ("paloalto", "SSH (Netmiko)", "SNMP v2c", "No", "Yes (XML API)"),
        ("mikrotik", "SSH (Netmiko)", "SNMP v2c", "No", "Yes"),
        ("aruba", "SSH (Netmiko)", "SNMP v2c/v3", "No", "Yes"),
        ("pfsense", "SSH (Netmiko)", "SNMP v2c", "No", "Yes (xmlrpc)"),
    ]
    w = [32, 36, 32, 22, 36]
    pdf.table_row(["Vendor", "SSH", "SNMP", "NETCONF", "RESTCONF"], w, header=True)
    for row in protos:
        pdf.table_row(list(row), w)

    # ===== SECTION 8: CONFIG MANAGEMENT =====
    pdf.add_page()
    pdf.section_title("8", "Configuration Management")

    pdf.sub_title("Backup Device Config")
    pdf.code_block("# Single device\npython run.py cli config backup core-switch-01\n\n# All devices\npython run.py cli config backup-all")

    pdf.sub_title("View & Compare Configs")
    pdf.code_block("# List backups for a device\npython run.py cli config history core-switch-01\n\n# Diff two backups\npython run.py cli config diff <backup-id-1> <backup-id-2>")

    pdf.sub_title("Deploy Configuration")
    pdf.code_block('# Deploy commands to a device\npython run.py cli config deploy core-switch-01 \\\n  --commands "interface GigabitEthernet0/1" \\\n  --commands "description Uplink to Router" \\\n  --commands "no shutdown"\n\n# Dry run (preview only)\npython run.py cli config deploy core-switch-01 \\\n  --commands "..." --dry-run')

    pdf.sub_title("Rollback")
    pdf.code_block("# Rollback to a previous config\npython run.py cli config rollback core-switch-01 <backup-id>")

    pdf.info_box("SAFETY", "Always use --dry-run first to preview changes before deploying to production devices. Config deployments are logged in the audit trail.")

    # ===== SECTION 9: MONITORING =====
    pdf.add_page()
    pdf.section_title("9", "Monitoring & Alerts")

    pdf.sub_title("Start Monitoring")
    pdf.code_block("# Poll a single device\npython run.py cli monitor poll core-switch-01\n\n# Poll all devices\npython run.py cli monitor poll-all\n\n# Start continuous monitoring (background)\npython run.py cli monitor start --interval 60")

    pdf.sub_title("View Metrics")
    pdf.code_block("# View latest metrics\npython run.py cli monitor show core-switch-01\n\n# Web dashboard: Monitoring tab with real-time charts")

    pdf.sub_title("Alert Rules")
    pdf.body_text("Default alert rules are created on init:")
    rules = [
        ("CPU Critical", "cpu_utilization > 90%", "critical"),
        ("Memory High", "memory_utilization > 85%", "warning"),
        ("Interface Errors", "error_count > 100", "warning"),
        ("Device Unreachable", "ping_loss = 100%", "critical"),
        ("High Latency", "latency > 200ms", "warning"),
    ]
    w = [50, 70, 40]
    pdf.table_row(["Rule", "Condition", "Severity"], w, header=True)
    for row in rules:
        pdf.table_row(list(row), w)

    pdf.ln(4)
    pdf.body_text("When monitoring detects a metric exceeding a threshold, alerts fire automatically. If automation runbooks are configured for that alert type, remediation begins autonomously.")

    # ===== SECTION 10: AUTOMATION =====
    pdf.add_page()
    pdf.section_title("10", "Automation & Runbooks")

    pdf.body_text("The automation engine executes YAML-defined runbooks in response to alerts, schedules, webhooks, or manual triggers. Runbooks are stored in data/runbooks/.")

    pdf.sub_title("View Runbooks")
    pdf.code_block("python run.py cli automation list")

    pdf.sub_title("Included Sample Runbooks")
    runbooks = [
        ("cpu-high-remediation", "alert", "Gathers CPU data, notifies, waits, re-checks, escalates"),
        ("nightly-config-backup", "schedule", "Backs up all configs daily at 02:00 UTC"),
        ("interface-error-remediation", "alert", "Clears counters, waits 5min, re-checks"),
        ("device-unreachable-triage", "alert", "Multi-source ping + port checks, escalates"),
        ("weekly-compliance-check", "schedule", "Weekly Saturday config audit"),
    ]
    w = [55, 25, 100]
    pdf.table_row(["Runbook", "Trigger", "Description"], w, header=True)
    for row in runbooks:
        pdf.table_row(list(row), w)

    pdf.ln(4)
    pdf.sub_title("Run a Runbook Manually")
    pdf.code_block("python run.py cli automation run cpu-high-remediation\n\n# With a specific device context\npython run.py cli automation run cpu-high-remediation \\\n  --device core-switch-01")

    pdf.sub_title("View Execution History")
    pdf.code_block("python run.py cli automation history\npython run.py cli automation show-exec <execution-id>")

    pdf.sub_title("View Scheduled Jobs")
    pdf.code_block("python run.py cli automation jobs")

    pdf.sub_title("Audit Log")
    pdf.code_block("python run.py cli automation audit")

    pdf.add_page()
    pdf.sub_title("Creating a Custom Runbook")
    pdf.body_text("Create a YAML file in data/runbooks/. Here's the structure:")
    pdf.code_block('name: "my-custom-runbook"\nversion: "1.0"\ndescription: "What this runbook does"\nenabled: true\ntags: ["custom"]\n\ntrigger:\n  type: "alert"          # alert | schedule | webhook | manual\n  alert_match:\n    rule_id: "rule-cpu-critical"\n    severity: ["critical"]\n\ncooldown:\n  per_device: 300        # Seconds before re-running for same device\n\nlimits:\n  max_duration_seconds: 600\n  max_concurrent: 1\n\nactions:\n  - name: "Step 1"\n    action: "run_command"\n    params:\n      device_id: "{{device_id}}"\n      command: "show processes cpu"\n    output_var: "cpu_output"\n    on_failure: "continue"\n    timeout: 30\n\n  - name: "Step 2"\n    action: "notify"\n    params:\n      channel: "slack"\n      message: "CPU info: {{cpu_output}}"')

    pdf.ln(3)
    pdf.sub_title("17 Available Action Types")
    actions = [
        ("run_command", "Execute CLI command via SSH"),
        ("poll_device", "Poll device health metrics"),
        ("backup_config", "Backup single device config"),
        ("backup_all", "Backup all device configs"),
        ("deploy_config", "Push config commands to device"),
        ("rollback_config", "Rollback to previous config"),
        ("check_interface_errors", "Check interface error counters"),
        ("check_device_health", "Full device health check"),
        ("ping_test", "ICMP ping test"),
        ("check_port", "TCP port connectivity check"),
        ("scan_subnet", "SNMP subnet discovery scan"),
        ("notify", "Send alert notification"),
        ("log", "Write to audit log"),
        ("wait", "Pause execution (seconds)"),
        ("condition", "Conditional branching"),
        ("escalate", "Escalation chain trigger"),
        ("http_request", "External HTTP API call"),
    ]
    w = [45, 135]
    pdf.table_row(["Action", "Description"], w, header=True)
    for row in actions:
        pdf.table_row(list(row), w)

    # ===== SECTION 11: AI CHAT =====
    pdf.add_page()
    pdf.section_title("11", "AI Chat Agent")

    pdf.body_text("The AI Chat agent uses Claude with 17 network operation tools. It understands natural language and can perform any operation the CLI can.")

    pdf.sub_title("Launch")
    pdf.code_block("python run.py chat\n\n# Or via the web dashboard: AI Chat tab")

    pdf.sub_title("Example Conversations")
    examples = [
        "Show me all devices and their status",
        "Backup the config on core-switch-01",
        "What's the CPU utilization on all switches?",
        "Deploy 'no shutdown' on interface Gi0/1 of switch-02",
        "Run the cpu-high-remediation runbook on fw-01",
        "List all active alerts",
        "Scan subnet 10.0.1.0/24 for new devices",
        "Show me the last 5 config backups for router-01",
    ]
    for ex in examples:
        pdf.bullet(f'"{ex}"')

    pdf.sub_title("Safety Levels")
    pdf.body_text("Every AI tool has a safety classification:")
    safety = [
        ("Safe", "Read-only operations: list devices, show metrics, view configs", "No confirmation needed"),
        ("Write", "Modifications: deploy config, add device, update settings", "Confirmation prompt"),
        ("Destructive", "Irreversible: delete device, rollback config, clear data", "Explicit confirmation required"),
    ]
    w = [30, 100, 50]
    pdf.table_row(["Level", "Examples", "Behavior"], w, header=True)
    for row in safety:
        pdf.table_row(list(row), w)

    # ===== SECTION 12: VENDORS =====
    pdf.add_page()
    pdf.section_title("12", "Supported Vendors & Platforms")

    vendors_detail = [
        ("Cisco IOS / IOS-XE", "cisco_ios", "Catalyst switches, ISR routers, ASR routers", "SSH, SNMP, NETCONF, RESTCONF"),
        ("Juniper JunOS", "juniper_junos", "EX switches, SRX firewalls, MX routers", "SSH, SNMP, NETCONF, RESTCONF"),
        ("Fortinet FortiOS", "fortinet", "FortiGate firewalls, FortiSwitch", "SSH, SNMP, REST API"),
        ("Palo Alto PAN-OS", "paloalto", "PA-series firewalls, Panorama", "SSH, SNMP, XML API"),
        ("MikroTik RouterOS", "mikrotik", "MikroTik routers, switches, APs", "SSH, SNMP, REST API"),
        ("Aruba / HPE", "aruba", "Aruba switches, CX series, APs", "SSH, SNMP, REST API"),
        ("pfSense", "pfsense", "pfSense/OPNsense firewalls", "SSH, SNMP, xmlrpc API"),
    ]
    for name, key, devices, protocols in vendors_detail:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*pdf.WHITE)
        pdf.cell(0, 8, f"{name}  (vendor key: {key})", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(*pdf.MUTED)
        pdf.set_x(20)
        pdf.cell(0, 6, f"Devices: {devices}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_x(20)
        pdf.cell(0, 6, f"Protocols: {protocols}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # ===== SECTION 13: PROJECT STRUCTURE =====
    pdf.add_page()
    pdf.section_title("13", "Project Structure")

    pdf.code_block("network_agent/\n"
                   "  run.py                    # Entry point\n"
                   "  config.yaml               # Global configuration\n"
                   "  requirements.txt          # Python dependencies\n"
                   "  .env                      # Secrets (API keys, encryption key)\n"
                   "  core/\n"
                   "    database.py             # SQLite with 11 tables\n"
                   "    models.py               # Pydantic models & enums\n"
                   "    credentials.py          # Fernet encryption manager\n"
                   "    connection_pool.py       # Async connection pooling\n"
                   "    exceptions.py           # 19 exception classes\n"
                   "  devices/\n"
                   "    base.py                 # BaseDevice ABC\n"
                   "    ssh_device.py           # Netmiko SSH wrapper\n"
                   "    snmp_device.py          # pysnmp SNMP wrapper\n"
                   "    netconf_device.py       # ncclient wrapper\n"
                   "    restconf_device.py      # httpx REST wrapper\n"
                   "    registry.py             # Device class registry\n"
                   "    vendors/               # 8 vendor implementations\n"
                   "  operations/\n"
                   "    config_manager.py       # Backup/deploy/diff/rollback\n"
                   "    monitor.py              # Health polling & metrics\n"
                   "    discovery.py            # SNMP/ping network scanning\n"
                   "    troubleshoot.py         # Diagnostics tools\n"
                   "  alerts/\n"
                   "    engine.py               # Alert evaluation & firing\n"
                   "    rules.py                # Default alert rules\n"
                   "    channels/               # Slack, email, webhook\n"
                   "  automation/\n"
                   "    engine.py               # Core orchestrator\n"
                   "    executor.py             # Runbook action runner\n"
                   "    actions.py              # 17 action type handlers\n"
                   "    runbook.py              # YAML parser & validator\n"
                   "    scheduler.py            # APScheduler cron jobs\n"
                   "    audit.py                # Audit trail logger\n"
                   "    webhook_ingress.py      # Inbound event API\n"
                   "  interfaces/\n"
                   "    cli/                    # Typer CLI commands\n"
                   "    web/                    # FastAPI dashboard + routes\n"
                   "    ai_agent/               # Claude tool-use agent\n"
                   "  data/\n"
                   "    runbooks/               # YAML runbook definitions\n"
                   "    network_agent.db        # SQLite database")

    # ===== SECTION 14: TROUBLESHOOTING =====
    pdf.add_page()
    pdf.section_title("14", "Troubleshooting")

    pdf.sub_title("Common Issues")

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*pdf.YELLOW)
    pdf.cell(0, 8, "\"ModuleNotFoundError\" when running", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(*pdf.TEXT)
    pdf.body_text("Make sure you've activated your virtual environment and installed requirements:")
    pdf.code_block("pip install -r requirements.txt")

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*pdf.YELLOW)
    pdf.cell(0, 8, "\"Connection refused\" when connecting to a device", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(*pdf.TEXT)
    pdf.body_text("Verify the device IP is correct and SSH/SNMP is enabled on the device:")
    pdf.code_block("python run.py cli diag ping 192.168.1.1\npython run.py cli diag port-check 192.168.1.1 22")

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*pdf.YELLOW)
    pdf.cell(0, 8, "\"Authentication failed\"", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(*pdf.TEXT)
    pdf.body_text("Check that the credential is properly assigned to the device and the username/password are correct:")
    pdf.code_block("python run.py cli credential list\npython run.py cli device show core-switch-01")

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*pdf.YELLOW)
    pdf.cell(0, 8, "Web dashboard not loading", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(*pdf.TEXT)
    pdf.body_text("Check that port 8080 is not in use and the init has been run:")
    pdf.code_block("python run.py init\npython run.py web --port 8081  # Use alternate port")

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*pdf.YELLOW)
    pdf.cell(0, 8, "AI Chat says \"API key not found\"", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(*pdf.TEXT)
    pdf.body_text("Set your Anthropic API key in the .env file:")
    pdf.code_block("ANTHROPIC_API_KEY=sk-ant-api03-...")

    pdf.ln(8)
    pdf.sub_title("Getting Help")
    pdf.bullet("CLI help: python run.py cli --help")
    pdf.bullet("Command help: python run.py cli <command> --help")
    pdf.bullet("Check logs in the terminal output for detailed error messages")
    pdf.bullet("Audit log: python run.py cli automation audit")

    # ===== SAVE =====
    output_path = "NetworkAgent_Setup_Guide.pdf"
    pdf.output(output_path)
    print(f"Guide generated: {output_path}")
    return output_path


if __name__ == "__main__":
    build_guide()
